### ISSUE TITLE
Create a UI to edit keyword/channel mapping

### ISSUE THREAD

**Issue by ruKurz** [assistify/support-form#2]
The parent channel of the discussion is determined by analyzing the content of the problem description (by a "keywords/channels matching table"). If the system is not able to infer a parent channel, a default parent channel is used.
- [x] There exists an UI that allows to define a keyword/channel matching table 
- [x] The "keywords/channels matching table" must be persistent

**Comment by jschirrmacher** [comment]
Users who have the role `config-expert` can use the UI on https://assistify.github.io/support-form/#/config
